name: TypeScript/React + Go
on:
  push:
    paths-ignore:
      - '*.md'
      - '**/.md'
jobs:
  linux:
      name: Ubuntu
      # This line is required to make Go see other containers, ie. postgres
      # See: https://github.community/t/services-name-resolution-error/16716/5
      container: golang:1.19-buster
      runs-on: ubuntu-latest
      services:
        # Label used to access the service container
        postgres:
          image: postgres
          env:
            POSTGRES_PASSWORD: password
          ports:
            # Maps tcp port 5432 on service container to the host
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      strategy:
        matrix:
          go: ['1.19']
      env:
        name: ubuntu
      steps:
        - name: Check out code
          uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: '16'

        - name: Frontend React/TypeScript Build And Lint
          run: |
            cd node/client
            npm install
            npm run build
            npm run lint

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Setup Database
          env:
            DATABASE_URL: "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"
          run: |
            go install github.com/amacneil/dbmate@v1.12.1
            dbmate --no-dump-schema migrate

        - name: Backend Unit and Integration Tests
          env:
            DATABASE_URL: "postgres://postgres:password@postgres:5432/postgres"
          run: |
            cd go/server/internal
            go test -tags dev ./...

        #- name: Setup Chrome
        #  uses: browser-actions/setup-chrome@latest
        
        # note(jae): 2021-07-20
        # this step requires "Frontend React/TypeScript Build" to run first.
        #
        # note(jae); 2021-07-20
        # this won't work right now, gets the error:
        # "e2etest_test.go:107: button click failed: chrome failed to start: "
        #- name: End-To-End Tests
        #  run: |
        #    chrome --version
        #    cd go/server
        #    cp config.example.json config.json
        #    cd e2etest
        #    go test
